version: '3.8'

networks:
  symfony-app:

services:

  # nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/configs/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - postgres
    networks:
      - symfony-app

  # php
  app:
    image: php:8.1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    networks:
      - symfony-app

  # postgres
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=symfony_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - symfony-app

  #mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - symfony-app